# Generated by Django 4.2.3 on 2023-12-30 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('phone_number', models.CharField(max_length=11)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.BooleanField(default=False)),
                ('status', models.CharField(default='Processing', max_length=100)),
                ('txn_id', models.CharField(max_length=15)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='CableService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('buy', models.FloatField(default=0.0)),
                ('mid', models.FloatField(default=0.0)),
                ('sell', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.BooleanField(default=False)),
                ('status', models.CharField(default='Processing', max_length=100)),
                ('txn_id', models.CharField(max_length=15)),
                ('amount', models.FloatField()),
                ('phone_number', models.CharField(max_length=11)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customeraccount')),
                ('airtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airtime', to='customer.airtime')),
                ('data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='customer.data')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=15)),
                ('amount', models.FloatField(default=0.0)),
                ('purpose', models.CharField(blank=True, max_length=19, null=True)),
                ('status', models.CharField(default='Processing', max_length=19)),
                ('date', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to='user.customeraccount')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='user.customeraccount')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('amount', models.FloatField(default=0.0)),
                ('email', models.EmailField(max_length=254)),
                ('ref', models.CharField(max_length=199)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Txn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customeraccount')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.bill')),
                ('topup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.topup')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.transfer')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('amount', models.FloatField(default=0.0)),
                ('product_code', models.CharField(max_length=49)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.provider')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=299)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('read', models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('disapproved', models.BooleanField(default=False)),
                ('reason', models.CharField(max_length=299)),
                ('amount', models.FloatField(default=0.0)),
                ('new_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('source_of_income', models.CharField(max_length=99)),
                ('period', models.CharField(choices=[('1 Week', '1 Week'), ('1 Month', '1 Month'), ('3 Months', '3 Months'), ('6 Months', '6 Months')], max_length=99)),
                ('till', models.DateField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(max_length=19)),
                ('customer_name', models.CharField(max_length=99)),
                ('customer_district', models.CharField(blank=True, max_length=99, null=True)),
                ('customer_reference', models.CharField(blank=True, max_length=99, null=True)),
                ('customer_address', models.CharField(max_length=99)),
                ('amount', models.FloatField(default=0.0)),
                ('tariff_code', models.CharField(blank=True, max_length=99, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('bsst_tokenvalue', models.CharField(blank=True, max_length=99, null=True)),
                ('standard_tokenvalue', models.CharField(blank=True, max_length=99, null=True)),
                ('utility_name', models.CharField(blank=True, max_length=99, null=True)),
                ('exchange_reference', models.CharField(blank=True, max_length=99, null=True)),
                ('token', models.CharField(blank=True, max_length=99, null=True)),
                ('unit', models.CharField(blank=True, max_length=99, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=99, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customeraccount')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.electricityservice')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.plan'),
        ),
        migrations.AddField(
            model_name='data',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.provider'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=15)),
                ('card_type', models.CharField(choices=[('VISA', 'VISA'), ('Verve', 'Verve'), ('MasterCard', 'MasterCard')], max_length=19)),
                ('card', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=9)),
                ('card_number', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('expires', models.DateField()),
                ('pin', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='CablePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=299)),
                ('amount', models.FloatField(default=0.0)),
                ('product_code', models.CharField(max_length=49)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.cableservice')),
            ],
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=99, null=True)),
                ('customer_number', models.CharField(blank=True, max_length=30, null=True)),
                ('card_number', models.CharField(max_length=30)),
                ('exchange_reference', models.CharField(blank=True, max_length=99, null=True)),
                ('customercare_referenceid', models.CharField(blank=True, max_length=99, null=True)),
                ('audit_referencenumber', models.CharField(blank=True, max_length=99, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customeraccount')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.cableplan')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.cableservice')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='cable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cable', to='customer.cable'),
        ),
        migrations.AddField(
            model_name='bill',
            name='electricity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electricity', to='customer.electricity'),
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='user.customeraccount')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary', to='user.customeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('modify_limit', models.BooleanField(default=False)),
                ('statement', models.BooleanField(default=False)),
                ('txn', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=9)),
                ('how', models.CharField(choices=[('Mobile', 'Mobile'), ('Card', 'Card'), ('USSD', 'USSD'), ('ATM', 'ATM')], max_length=49)),
                ('which', models.CharField(choices=[('UTU', 'UTU'), ('UTO', 'UTO'), ('Patridge Bank', 'Patridge Bank'), ('TOPUP', 'TOPUP'), ('BILL', 'BILL')], max_length=49)),
                ('detail', models.CharField(max_length=299)),
                ('amount', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.bill')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.card')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.loan')),
                ('topup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.topup')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.transfer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='airtime',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.provider'),
        ),
    ]
