# Generated by Django 4.2.3 on 2023-12-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_provider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='product_code',
            field=models.CharField(default='MSCode', max_length=49),
            preserve_default=False,
        ),
    ]
