# Generated by Django 4.2.3 on 2023-12-24 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_cableplan_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.cableplan'),
        ),
    ]
