# Generated by Django 4.2.3 on 2023-12-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_bill_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='customer_name',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='cable',
            name='customer_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
