# Generated by Django 4.2.3 on 2023-12-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_cable_customer_name_cable_customer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='audit_referencenumber',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='cable',
            name='customercare_referenceid',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='cable',
            name='exchange_reference',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
