# Generated by Django 4.2.3 on 2023-12-27 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customeraccount_account_name_and_more'),
        ('customer', '0008_cable_audit_referencenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(max_length=19)),
                ('customer_name', models.CharField(max_length=99)),
                ('customer_district', models.CharField(blank=True, max_length=99, null=True)),
                ('customer_address', models.CharField(max_length=99)),
                ('amount', models.FloatField(default=0.0)),
                ('tariff_code', models.CharField(blank=True, max_length=99, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('third_partycode', models.CharField(blank=True, max_length=99, null=True)),
                ('service_band', models.CharField(blank=True, max_length=99, null=True)),
                ('customer_details', models.CharField(blank=True, max_length=99, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=499, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=99, null=True)),
                ('access_code', models.CharField(blank=True, max_length=99, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
            ],
        ),
        migrations.RemoveField(
            model_name='orphanageplan',
            name='service',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='account',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='service',
        ),
        migrations.RemoveField(
            model_name='travelbill',
            name='service',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='orphanage',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='travel',
        ),
        migrations.DeleteModel(
            name='Orphanage',
        ),
        migrations.DeleteModel(
            name='OrphanagePlan',
        ),
        migrations.DeleteModel(
            name='OrphanageService',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
        migrations.DeleteModel(
            name='TravelBill',
        ),
        migrations.DeleteModel(
            name='TravelService',
        ),
        migrations.AddField(
            model_name='electricity',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.electricityservice'),
        ),
        migrations.AddField(
            model_name='bill',
            name='electricity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electricity', to='customer.electricity'),
        ),
    ]
