# Generated by Django 4.2.3 on 2023-12-28 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_electricity_bsst_tokenvalue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricity',
            name='access_code',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='customer_details',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='service_band',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='third_partycode',
        ),
    ]
