# Generated by Django 4.2.3 on 2023-12-30 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customeraccount_account_name_and_more'),
        ('customer', '0011_remove_electricity_access_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('amount', models.FloatField(default=0.0)),
                ('email', models.EmailField(max_length=254)),
                ('ref', models.CharField(max_length=199)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customeraccount')),
            ],
        ),
    ]
