# Generated by Django 4.2.3 on 2023-09-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='account_name',
            field=models.CharField(db_index=True, max_length=299),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='account_number',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='account_name',
            field=models.CharField(db_index=True, max_length=299),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_ID',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True, unique=True),
        ),
    ]
